version: '3.8'
services:
  django:
    build: .
    container_name: django
    command: sh -c  "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
       - ./:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  celery:
    build: .
    command: sh -c "sleep 60 && celery -A core worker -l info --pool=solo"
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - django
      - rabbitmq
    networks:
      - mynetwork
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-api
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dados:/var/lib/rabbitmq/
    networks:
      - mynetwork

networks:
  mynetwork:
