# Generated by Django 5.0 on 2023-12-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_statusemprestimo_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StatusEmprestimo',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='valor_do_emprestimo',
            new_name='valor_emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='Aguardando', max_length=10),
        ),
        migrations.AddField(
            model_name='campoproposta',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emprestimo'),
        ),
    ]
