# Generated by Django 5.0 on 2023-12-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campoproposta_delete_statusemprestimo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampoProposta',
        ),
    ]
