# Generated by Django 5.0 on 2023-12-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Aprovado'), ('2', 'Negado')], max_length=1)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emprestimo')),
            ],
        ),
    ]
