# Generated by Django 5.0 on 2023-12-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_statusemprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusemprestimo',
            name='emprestimo',
        ),
    ]
